module ModSpox

    RFC = {
        # basic
        :INVITE => {:value => :INVITE, :handlers => ['Invite']},
        :JOIN => {:value => :JOIN, :handlers => ['Join']},
        :KICK => {:value => :KICK, :handlers => ['Kick']},
        :MODE => {:value => :MODE, :handlers => ['Mode']},
        :NICK => {:value => :NICK, :handlers => ['Nick']},
        :NOTICE => {:value => :NOTICE, :handlers => ['Notice']},
        :PART => {:value => :PART, :handlers => ['Part']},
        :PING => {:value => :PING, :handlers => ['Ping']},
        :PONG => {:value => :PONG, :handlers => ['Pong']},
        :PRIVMSG => {:value => :PRIVMSG, :handlers => ['Privmsg']},
        :QUIT => {:value => :QUIT, :handlers => ['Quit']},
        #client server messages#
        :RPL_WELCOME => {:value => '001', :handlers => ['Welcome']},
        :RPL_YOURHOST => {:value => '002'},
        :RPL_CREATED => {:value => '003', :handlers => ['Created']},
        :RPL_MYINFO => {:value => '004', :handlers => ['MyInfo']},
        :RPL_BOUNCE => {:value => '005', :handlers => ['Bounce']},
        #response replies#
        :RPL_USERHOST => {:value => '302', :handlers => ['UserHost']},
        :RPL_ISON => {:value => '303'},
        :RPL_AWAY => {:value => '301'},
        :RPL_UNAWAY => {:value => '305'},
        :RPL_NOWAWAY => {:value => '306'},
        :RPL_WHOISIDENTIFIED => {:value => '307', :handlers => ['Whois']},
        :RPL_WHOISUSER => {:value => '311', :handlers => ['Whois']},
        :RPL_WHOISSERVER => {:value => '312', :handlers => ['Whois']},
        :RPL_WHOISOPERATOR => {:value => '313', :handlers => ['Whois']},
        :RPL_WHOISIDLE => {:value => '317', :handlers => ['Whois']},
        :RPL_ENDOFWHOIS => {:value => '318', :handlers => ['Whois']},
        :RPL_WHOISCHANNELS => {:value => '319', :handlers => ['Whois']},
        :RPL_WHOWASUSER => {:value => '314'},
        :RPL_ENDOFWHOWAS => {:value => '369'},
        :RPL_LISTSTART => {:value => '321'},
        :RPL_LIST => {:value => '322'},
        :RPL_LISTEND => {:value => '323'},
        :RPL_UNIQOPIS => {:value => '325'},
        :RPL_CHANNELMODEIS => {:value => '324'},
        :RPL_NOTOPIC => {:value => '331', :handlers => ['Topic']},
        :RPL_TOPIC => {:value => '332', :handlers => ['Topic']},
        :RPL_TOPICINFO => {:value => '333', :handlers => ['Topic']},
        :RPL_INVITING => {:value => '341'},
        :RPL_SUMMONING => {:value => '342'},
        :RPL_INVITELIST => {:value => '346'},
        :RPL_ENDOFINVITELIST => {:value => '347'},
        :RPL_EXCEPTLIST => {:value => '348'},
        :RPL_ENDOFEXCEPTLIST => {:value => '349'},
        :RPL_VERSION => {:value => '351'},
        :RPL_WHOREPLY => {:value => '352', :handlers => ['Who']},
        :RPL_ENDOFWHO => {:value => '315', :handlers => ['Who']},
        :RPL_NAMREPLY => {:value => '353', :handlers => ['Names']},
        :RPL_ENDOFNAMES => {:value => '366', :handlers => ['Names']},
        :RPL_LINKS => {:value => '364'},
        :RPL_ENDOFLINKS => {:value => '365'},
        :RPL_BANLIST => {:value => '367'},
        :RPL_ENDOFBANLIST => {:value => '368'},
        :RPL_INFO => {:value => '371'},
        :RPL_ENDOFINFO => {:value => '374'},
        :RPL_MOTDSTART => {:value => '375', :handlers => ['Motd']},
        :RPL_MOTD => {:value => '372', :handlers => ['Motd']},
        :RPL_ENDOFMOTD => {:value => '376', :handlers => ['Motd']},
        :RPL_YOUREOPER => {:value => '381'},
        :RPL_REHASHING => {:value => '382'},
        :RPL_YOURESERVICE => {:value => '383'},
        :RPL_TIME => {:value => '391'},
        :RPL_USERSSTART => {:value => '392'},
        :RPL_USERS => {:value => '393'},
        :RPL_ENDOFUSERS => {:value => '394'},
        :RPL_NOUSERS => {:value => '395'},
        :RPL_TRACELINK => {:value => '200'},
        :RPL_TRACECONNECTING => {:value => '201'},
        :RPL_TRACEHANDSHAKE => {:value => '202'},
        :RPL_TRACEUNKNOWN => {:value => '203'},
        :RPL_TRACEOPERATOR => {:value => '204'},
        :RPL_TRACEUSER => {:value => '205'},
        :RPL_TRACESERVER => {:value => '206'},
        :RPL_TRACESERVICE => {:value => '207'},
        :RPL_TRACENEWTYPE => {:value => '208'},
        :RPL_TRACECLASS => {:value => '209'},
        :RPL_TRACERECONNECT => {:value => '210'},
        :RPL_TRACELOG => {:value => '261'},
        :RPL_TRACEEND => {:value => '262'},
        :RPL_STATSLINKINFO => {:value => '211'},
        :RPL_STATSCOMMANDS => {:value => '212'},
        :RPL_ENDOFSTATS => {:value => '219'},
        :RPL_STATSUPTIME => {:value => '242'},
        :RPL_STATSOLINE => {:value => '243'},
        :RPL_UMODEIS => {:value => '221'},
        :RPL_SERVLIST => {:value => '234'},
        :RPL_SERVLISTEND => {:value => '235'},
        :RPL_LUSERCLIENT => {:value => '251', :handlers => ['LuserClient']},
        :RPL_LUSEROP => {:value => '252', :handlers => ['LuserOp']},
        :RPL_LUSERUNKNOWN => {:value => '253', :handlers => ['LuserUnknown']},
        :RPL_LUSERCHANNELS => {:value => '254', :handlers => ['LuserChannels']},
        :RPL_LUSERME => {:value => '255', :handlers => ['LuserMe']},
        :RPL_ADMINME => {:value => '256'},
        :RPL_ADMINLOC1 => {:value => '257'},
        :RPL_ADMINLOC2 => {:value => '258'},
        :RPL_ADMINEMAIL => {:value => '259'},
        :RPL_TRYAGAIN => {:value => '263'},
        #error messages#
        :ERR_NOSUCHNICK => {:value => '401'},
        :ERR_NOSUCHSERVER => {:value => '402'},
        :ERR_NOSUCHCHANNEL => {:value => '403'},
        :ERR_CANNOTSENDTOCHAN => {:value => '404'},
        :ERR_TOOMANYCHANNELS => {:value => '405'},
        :ERR_WASNOSUCHNICK => {:value => '406'},
        :ERR_TOOMANYTARGETS => {:value => '407'},
        :ERR_NOSUCHSERVICE => {:value => '408'},
        :ERR_NOORIGIN => {:value => '409'},
        :ERR_NORECIPIENT => {:value => '411'},
        :ERR_NOTEXTTOSEND => {:value => '412'},
        :ERR_NOTOPLEVEL => {:value => '413'},
        :ERR_WILDTOPLEVEL => {:value => '413'},
        :ERR_BADMASK => {:value => '415'},
        :ERR_UNKNOWNCOMMAND => {:value => '421'},
        :ERR_NOMOTD => {:value => '422'},
        :ERR_NOADMININFO => {:value => '423'},
        :ERR_FILEERROR => {:value => '424'},
        :ERR_NONICKNAMEGIVEN => {:value => '431'},
        :ERR_ERRONEOUSNICKNAME => {:value => '432', :handlers => ['BadNick']},
        :ERR_NICKNAMEINUSE => {:value => '433', :handlers => ['NickInUse']},
        :ERR_NICKCOLLISION => {:value => '436'},
        :ERR_UNAVAILRESOURCE => {:value => '437'},
        :ERR_USERNOTINCHANNEL => {:value => '441'},
        :ERR_NOTONCHANNEL => {:value => '442'},
        :ERR_USERONCHANNEL => {:value => '443'},
        :ERR_NOLOGIN => {:value => '444'},
        :ERR_SUMMONDISABLED => {:value => '445'},
        :ERR_USERDISABLED => {:value => '446'},
        :ERR_NOTREGISTERED => {:value => '451'},
        :ERR_NEEDMOREPARAMS => {:value => '461'},
        :ERR_ALREADYREGISTERED => {:value => '462'},
        :ERR_NOPERMFORHOST => {:value => '463'},
        :ERR_PASSWDMISMATCH => {:value => '464'},
        :ERR_YOUREBANNEDCREEP => {:value => '465'},
        :ERR_YOUWILLBEBANNED => {:value => '466'},
        :ERR_KEYSET => {:value => '467'},
        :ERR_CHANNELISFULL => {:value => '471'},
        :ERR_UNKNOWNMODE => {:value => '472'},
        :ERR_INVITEONLYCHAN => {:value => '473'},
        :ERR_BANNEDFROMCHAN => {:value => '474'},
        :ERR_BADCHANNELKEY => {:value => '475'},
        :ERR_BADCHANMASK => {:value => '476'},
        :ERR_NOCHANMODES => {:value => '477'},
        :ERR_BANLISTFULL => {:value => '478'},
        :ERR_NOPRIVILEGES => {:value => '481'},
        :ERR_CHANOPRIVSNEEDED => {:value => '482'},
        :ERR_CANTKILLSERVER => {:value => '483'},
        :ERR_RESTRICTED => {:value => '484'},
        :ERR_UNIQOPPRIVSNEEDED => {:value => '485'},
        :ERR_NOOPERHOST => {:value => '491'},
        :ERR_UMODEUNKNOWNFLAG => {:value => '501'},
        :ERR_USERSDONTMATCH => {:value => '502'},
        #extras#
        :RPL_SERVICEINFO => {:value => '231'},
        :RPL_ENDOFSERVICES => {:value => '232'},
        :RPL_SERVICE => {:value => '233'},
        :RPL_NONE => {:value => '300'},
        :RPL_WHOISCHANOP => {:value => '316'},
        :RPL_KILLDONE => {:value => '361'},
        :RPL_CLOSING => {:value => '362'},
        :RPL_CLOSEEND => {:value => '363'},
        :RPL_INFOSTART => {:value => '373'},
        :RPL_MYPORTIS => {:value => '384'},
        :RPL_STATSCLINE => {:value => '213'},
        :RPL_STATSNLINE => {:value => '214'},
        :RPL_STATSILINE => {:value => '215'},
        :RPL_STATSKLINE => {:value => '216'},
        :RPL_STATSQLINE => {:value => '217'},
        :RPL_STATSYLINE => {:value => '218'},
        :RPL_STATSVLINE => {:value => '240'},
        :RPL_STATSLLINE => {:value => '241'},
        :RPL_STATSHLINE => {:value => '244'},
        :RPL_STATSSLINE => {:value => '244'},
        :RPL_STATSPING => {:value => '246'},
        :RPL_STATSBLINE => {:value => '247'},
        :RPL_STATSDLINE => {:value => '250'},
        :ERR_NOSERVICEHOST => {:value => '492'}
    }
    # i feel kinda dirty after that, but hey, lets keep things interesting!
end